import React, { useCallback, useState } from "react";
import { View, Text, Pressable, StyleSheet, ScrollView, RefreshControl, ActivityIndicator } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { LinearGradient } from "expo-linear-gradient";
import { Ionicons } from "@expo/vector-icons";
import * as WebBrowser from "expo-web-browser";

import { alertsApi } from "@/src/api/alerts";
import type { AppNotification } from "@/src/types";
import { WEBSITE_URL } from "@/src/constants/config";
import { colors, spacing, radius, fontSize, font, shadow } from "@/src/constants/theme";

function timeAgo(iso: string): string {
  const diffMs = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diffMs / 60000);
  if (mins < 1) return "kounye a";
  if (mins < 60) return `${mins}min`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}è`;
  return `${Math.floor(hrs / 24)}j`;
}

// "Hot Matches" = notifications actually generated by the Deal Alert engine
// (type "deal_alert") — real matches, not a fabricated feed.
function isMatchNotification(n: AppNotification): boolean {
  return n.type === "deal_alert";
}

export default function HotMatchesScreen() {
  const [notifications, setNotifications] = useState<AppNotification[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async (isRefresh = false) => {
    if (isRefresh) setRefreshing(true);
    else setLoading(true);
    try {
      setNotifications(await alertsApi.getNotifications());
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useFocusEffect(
    useCallback(() => {
      load();
    }, [load]),
  );

  const matches = notifications.filter(isMatchNotification);

  const openDeal = async (n: AppNotification) => {
    if (!WEBSITE_URL || !n.link) return;
    await WebBrowser.openBrowserAsync(`${WEBSITE_URL}${n.link}`);
  };

  if (loading) {
    return (
      <SafeAreaView style={styles.loadingContainer} edges={["top", "bottom"]}>
        <ActivityIndicator color={colors.brandPrimary} size="large" />
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.safeArea} edges={["top", "bottom"]}>
      <View style={styles.header}>
        <Text style={styles.title}>🔥 Hot Matches</Text>
        <Text style={styles.subtitle}>Nou jwenn kèk opòtinite ki ka enterese w.</Text>
      </View>

      <ScrollView
        contentContainerStyle={styles.scrollContent}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.brandPrimary} />}
      >
        {matches.length === 0 ? (
          <View style={styles.emptyState}>
            <View style={styles.emptyIconWrap}>
              <Ionicons name="flame-outline" size={24} color={colors.onSurfaceTertiary} />
            </View>
            <Text style={styles.emptyTitle}>Pa gen match kounye a.</Text>
            <Text style={styles.emptySubtitle}>Lè yon pwodwi matche youn nan alèt ou yo, l ap parèt isit la.</Text>
          </View>
        ) : (
          matches.map((n) => (
            <LinearGradient
              key={n.id}
              colors={[colors.brandPrimary, colors.brandSecondary]}
              style={styles.matchCard}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
            >
              <View style={styles.matchHeaderRow}>
                <Ionicons name="flame" size={16} color="#FFD166" />
                <Text style={styles.matchBadgeText}>NEW MATCH</Text>
                <Text style={styles.matchTime}>{timeAgo(n.createdAt)}</Text>
              </View>
              <Text style={styles.matchMessage}>{n.message}</Text>
              <View style={styles.matchActions}>
                <Pressable style={styles.matchPrimaryButton} onPress={() => openDeal(n)} testID={`hot-match-view-${n.id}`}>
                  <Text style={styles.matchPrimaryButtonText}>View Deal</Text>
                </Pressable>
              </View>
            </LinearGradient>
          ))
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.surfaceSecondary },
  loadingContainer: { flex: 1, backgroundColor: colors.surfaceSecondary, alignItems: "center", justifyContent: "center" },
  header: { padding: spacing.lg, paddingBottom: spacing.sm },
  title: { fontSize: fontSize.xl, fontFamily: font.medium, color: colors.onSurface },
  subtitle: { fontSize: fontSize.sm, color: colors.onSurfaceSecondary, marginTop: 2 },
  scrollContent: { paddingHorizontal: spacing.lg, paddingBottom: spacing["3xl"] },

  matchCard: { borderRadius: radius.lg, padding: spacing.lg, marginBottom: spacing.md, ...shadow.raised },
  matchHeaderRow: { flexDirection: "row", alignItems: "center", gap: spacing.xs },
  matchBadgeText: { color: colors.onBrandPrimary, fontSize: fontSize.sm, fontFamily: font.medium, letterSpacing: 0.5, flex: 1 },
  matchTime: { color: "rgba(255,255,255,0.75)", fontSize: fontSize.sm },
  matchMessage: { color: colors.onBrandPrimary, fontSize: fontSize.base, marginTop: spacing.sm, lineHeight: 20 },
  matchActions: { marginTop: spacing.md },
  matchPrimaryButton: { backgroundColor: colors.surface, borderRadius: radius.pill, paddingVertical: spacing.sm, alignItems: "center" },
  matchPrimaryButtonText: { color: colors.brandPrimary, fontSize: fontSize.sm, fontFamily: font.medium },

  emptyState: { alignItems: "center", backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.xl, marginTop: spacing.lg, ...shadow.card },
  emptyIconWrap: {
    width: 44,
    height: 44,
    borderRadius: radius.pill,
    backgroundColor: colors.surfaceSecondary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.sm,
  },
  emptyTitle: { fontSize: fontSize.base, color: colors.onSurface, fontFamily: font.medium, textAlign: "center" },
  emptySubtitle: { fontSize: fontSize.sm, color: colors.onSurfaceSecondary, textAlign: "center", marginTop: spacing.xs },
});
